datasets:
  - name: "swdf"

connections:
  - name: "Tentris"
    endpoint: "http://localhost:81/sparql"
    version: "latest"

tasks:
  - className: "Stresstest"
    configuration:
      timeLimit: 6000
      queryHandler:
        className: "InstancesQueryHandler"

      workers:
        - threads: 1
          className: "SPARQLWorker"
          queriesFile: "/home/fabian/dev/bachelor/Basilisk/example_benchmark/swdf-queries.txt"

storages:
  - className: "NTFileStorage"
    configuration:
      fileName: ".data/iguana-results.nt"