version: '3.0'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  fuseki:
    image: fuseki
    command: "--tdb2 --loc databases/DB2 /results"
    ports:
      - "3030:3030"
    volumes:
      - ./.data/fuseki/logs:/fuseki/logs
      - ./.data/fuseki/databases:/fuseki/databases