spring:
  application:
    name: repository-service
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      platform: h2
  datasource:
    url: 'jdbc:h2:file:./data/databases/services/repository-service-DB'
    username: basilisk
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: rabbitmq
    port: '5672'
    username: guest
    password: guest

core:
  timing:
    timeout: 20

server:
  port: '8080'

rabbitmq:
  benchmarks:
    exchange: benchmarkExchange
    jobQueue: jobQueue
    resultQueue: resultQueue
    routingKeys:
      job: jobKey
      result: resultKey

proxies:
  docker:
    registryUrl: https://registry.hub.docker.com