spring:
  application:
    name: jobs-managing-service
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      platform: h2
  datasource:
    url: 'jdbc:h2:file:./.data/jobs-managing-service-DB'
    username: basilisk
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: rabbitmq
    port: '5672'
    username: guest
    password: guest

server:
  port: '8081'

rabbitmq:
  hooks:
    exchange: hooksExchange

    repoQueue: repoQueue
    repoRoutingKey: repoRoutingKey

    hookEventQueue: hookEventQueue
    hookEventRoutingKey: hookEventRoutingKey

  benchmarks:
    exchange: benchmarkExchange
    jobQueue: jobQueue
    resultQueue: resultQueue
    routingKeys:
      job: jobKey
      result: resultKey
