spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      platform: h2
  datasource:
    url: 'jdbc:h2:file:./data/myDB'
    username: basilisk
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

core:
  timing:
    timeout: 10

server:
  port: '8080'

rabbitmq:
  hooks:
    exchange: hooksExchange
    git:
      repoQueue: gitRepoQueue
      commitQueue: gitCommitQueue
      routingKeys:
        repo: gitRepoKey
        commit: gitCommitKey
    docker:
      repoQueue: dockerRepoQueue
      tagQueue: dockerTagQueue
      routingKeys:
        repo: dockerRepoKey
        tag: dockerTagKey

proxies:
  docker:
    apihost: https://registry.hub.docker.com