spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      platform: h2
  datasource:
    url: 'jdbc:h2:file:./.data/benchmark-service-DB'
    username: basilisk
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: '5672'
    username: guest
    password: guest
  jackson:
    default-property-inclusion: non_null

server:
  port: '8082'

docker:
  dockerHost: 'unix:///var/run/docker.sock'
  hostPort: 81

iguana:
  iguanaPath: '/home/fabian/dev/bachelor/iguana/'
  configFileDirectory: '/home/fabian/dev/bachelor/Basilisk/.data/iguana-configs'
  placeholders:
    dataSetPath: 'dataSetPath'
    dataSetName: 'dataSetName'
  resultStorage:
    className: 'TriplestoreStorage' # 'NTFileStorage' #
    configuration:
      endpoint: 'http://localhost:3030/results/sparql'
      updateEndpoint: 'http://localhost:3030/results/update'
      fileName: '/home/fabian/dev/bachelor/Basilisk/.data/iguana-results.nt'

rabbitmq:
  benchmarks:
    exchange: benchmarkExchange
    jobQueue: jobQueue
    resultQueue: resultQueue
    routingKeys:
      job: jobKey
      result: resultKey