docker:
  localhost: true

spring:
  rabbitmq:
    host: localhost
  datasource:
    url: 'jdbc:h2:file:/mnt/d/Development/Bachelor/data/benchmark-service-DB'

iguana:
  shell: '/usr/bin/bash'
  iguanaPath: '/home/fabian/dev/bachelor/iguana/iguana-3.3.0.jar'
  configFileDirectory: '/home/fabian/dev/bachelor/Basilisk/.data/iguana-configs'
  resultStorage:
    className: 'NTFileStorage'  #'TriplestoreStorage' #
    configuration:
      endpoint: 'http://localhost:3030/results/sparql'
      updateEndpoint: 'http://localhost:3030/results/update'
      fileName: '/home/fabian/dev/bachelor/Basilisk/.data/iguana-results2.nt'
