spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      platform: h2
  datasource:
    url: 'jdbc:h2:file:./.data/benchmark-service-DB'
    username: basilisk
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: '5672'
    username: guest
    password: guest
  jackson:
    default-property-inclusion: non_null

server:
  port: '8082'

docker:
  dockerHost: 'unix:///var/run/docker.sock'
  hostPort: 81

iguana:
  configFileDirectory: '.data/iguana-configs'
  resultsFile: '.data/iguana-results.nt'
  placeholders:
    dataSetPath: 'dataSetPath'
    dataSetName: 'dataSetName'
  resultStorage:
    endpoint: 'localhost'
    updateEndpoint: 'localhost/update'
    user: 'guest'
    password: 'guest'

rabbitmq:
  benchmarks:
    exchange: benchmarkExchange
    jobQueue: jobQueue
    resultQueue: resultQueue
    routingKeys:
      job: jobKey
      result: resultKey