spring:
  application:
    name: benchmark-service
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      platform: h2
  datasource:
    url: 'jdbc:h2:file:./.data/benchmark-service-DB'
    username: basilisk
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: rabbitmq
    port: '5672'
    username: guest
    password: guest
  jackson:
    default-property-inclusion: non_null

server:
  port: '8082'

docker:
  dockerHost: 'unix:///var/run/docker.sock'
  hostPort: 81
  networkName: 'basilisk_basilisk'
  containerName: 'triplestore'

benchmark:
  startInterval: 10

iguana:
  shell: '/bin/sh'
  iguanaPath: '/iguana/iguana-3.3.0.jar'
  configFileDirectory: '/iguana-configs'
  placeholders:
    dataSetPath: 'dataSetPath'
    dataSetName: 'dataSetName'
  resultStorage:
    className: 'TriplestoreStorage' # 'NTFileStorage' #
    configuration:
      endpoint: 'http://fuseki:3030/results/sparql'
      updateEndpoint: 'http://fuseki:3030/results/update'
      fileName: '/home/fabian/dev/bachelor/Basilisk/.data/iguana-results.nt'

rabbitmq:
  benchmarks:
    exchange: benchmarkExchange
    jobQueue: jobQueue
    resultQueue: resultQueue
    routingKeys:
      job: jobKey
      result: resultKey
